version: '3.7'
services:
  gateway:
    build:
      context: ./gateway
    container_name: gateway
    depends_on: 
      - data_analysis
      - frontend
    ports:
      - "80:80"
    #  - "5000:5000"
    networks:
      - farm_net

  data_analysis:
    build:
      context: ./dataAnalysis
    container_name: data_analysis
    ports:
      - "5000:5000"
    command: ["python", "app.py"]
    networks:
      - farm_net

  frontend:
    build:
      context: ./FarmPredictor
    container_name: frontend
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver","0:8000"]
    networks:
      - farm_net
  database:
    image: mariadb:10.8.2
    container_name: database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=farm
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    networks:
      - farm_net
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "9000:9000"
    depends_on: 
      database:
        condition: service_healthy
      
    
    command: ["npm", "start"]
    networks:
      - farm_net

networks:
  farm_net:
